import { Platform } from 'react-native';

export const Colors = {
  dark: {
    background: '#0B0B1E',
    surface: '#151530',
    surfaceLight: '#1E1E3F',
    surfaceLighter: '#282850',
    primary: '#8B5CF6',
    primaryLight: '#A78BFA',
    primaryDark: '#6D28D9',
    accent: '#F472B6',
    text: '#F1F1F6',
    textSecondary: '#9CA3AF',
    textMuted: '#555577',
    border: '#252545',
    icon: '#9CA3AF',
    tint: '#8B5CF6',
    tabIconDefault: '#555577',
    tabIconSelected: '#8B5CF6',
    success: '#4ADE80',
    warning: '#FBBF24',
  },
  light: {
    background: '#0B0B1E',
    surface: '#151530',
    surfaceLight: '#1E1E3F',
    surfaceLighter: '#282850',
    primary: '#8B5CF6',
    primaryLight: '#A78BFA',
    primaryDark: '#6D28D9',
    accent: '#F472B6',
    text: '#F1F1F6',
    textSecondary: '#9CA3AF',
    textMuted: '#555577',
    border: '#252545',
    icon: '#9CA3AF',
    tint: '#8B5CF6',
    tabIconDefault: '#555577',
    tabIconSelected: '#8B5CF6',
    success: '#4ADE80',
    warning: '#FBBF24',
  },
};

export const Fonts = Platform.select({
  ios: {
    sans: 'system-ui',
    serif: 'ui-serif',
    rounded: 'ui-rounded',
    mono: 'ui-monospace',
  },
  default: {
    sans: 'normal',
    serif: 'serif',
    rounded: 'normal',
    mono: 'monospace',
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
